RudeAnchorSN/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RudeAnchorSN.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var userIdentity = User?.Identity;

            if (userIdentity != null && userIdentity.IsAuthenticated)
                return RedirectToAction("Index", "User");

            return View();
        }
    }
}

RudeAnchorSN/Controllers/SignInController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.DataLayer.Exceptions;
using RudeAnchorSN.LogicLayer.Services;
using System.Security.Authentication;
using System.Security.Claims;

namespace RudeAnchorSN.Controllers
{
    [Route("[controller]")]
    public class SignInController : Controller
    {
        private readonly ILogger<SignInController> _logger;
        private readonly IUserService _userService;

        public SignInController(
            ILogger<SignInController> logger,
            IUserService userService)
        {
            _logger = logger;
            _userService = userService;
        }

        [HttpPost]
        public async Task<IActionResult> Index(string email, string password)
        {
            try
            {
                var _user = await _userService.AuthenticateUser(email, password);

                if (_user != null)
                {
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimsIdentity.DefaultNameClaimType, _user?.Email)
                    };

                    ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "AppCookie");

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                }
            }
            catch (UserNotFoundException)
            {
                TempData["Error"] = "Пользователь не найден";

                return RedirectToAction("Index", "Home");
            }
            catch (AuthenticationException)
            {
                TempData["Error"] = "Неверный пароль";

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "User");
        }
    }
}

RudeAnchorSN/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "RudeAnchor Social Network - Home Page";
}

@section css{
    <link href="/css/forms.css" rel="stylesheet" />
    <link href="/css/home.css" rel="stylesheet" />
}

<div class="wrapper">
    <div class="spoiler-block">
        <h1>
            Добро пожаловать в соц сеть
        </h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
    </div>

<div class="home-forms">
    <div class="authorization-form form-container">
        @using (Html.BeginForm("Index", "SignIn", FormMethod.Post))
        {
            <div class="form-line">
                <div class="form-label">Email</div>
                <input type="text" name="Email" required />
            </div>

            <div class="form-line">
                <div class="form-label">Пароль</div>
                <input type="password" name="Password" required />
            </div>

            <div class="form-line">
                <button type="submit">Авторизация</button>
            </div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="error-text authentication-error">@TempData["Error"]</div>
        }
    </div>

    <div class="registration-form form-container">
        @using (Html.BeginForm("Index", "SignUp", FormMethod.Get))
        {
            <div class="form-line">
                <div class="form-label">Имя</div>
                <input type="text" name="FirstName" required />
            </div>

            <div class="form-line">
                <div class="form-label">Фамилия</div>
                <input type="text" name="LastName" required />
            </div class="form-line">

            <div class="form-line">
                <div class="form-label">Дата рождения</div>
                <input type="date" name="BirthDate" required />
            </div>

            <div class="form-line">
                <button type="submit">Регистрация</button>
            </div>
        }
    </div>
</div>
</div>