RudeAnchorSN/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Services;
using RudeAnchorSN.LogicLayer.Models;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class FriendsController : Controller
    {
        private readonly ILogger<FriendsController> _logger;
        private readonly IUserService _userService;
        private readonly IFriendService _friendService;
        private readonly IRequestService _requestService;

        public FriendsController(
            ILogger<FriendsController> logger,
            IUserService userService,
            IFriendService friendService,
            IRequestService requestService)
        {
            _logger = logger;
            _userService = userService;
            _friendService = friendService;
            _requestService = requestService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);
            var friends = new FriendsViewModel();

            if (user != null)
            {
                friends.PendingRequests = await _requestService.GetPending(user.Id);
                friends.Friends = user.Friends;
            }

            return View(friends);
        }

        [HttpGet]
        [Route("Add")]
        public async Task<IActionResult> Add()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);
            var users = new List<UserModel>();
                
            if (user != null)
                users = await _userService.GetUsers(user.Id);

            return View(users);
        }

        [HttpGet]
        [Route("Add/{id}")]
        public async Task<IActionResult> Add(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                var request = await _requestService.GetRequest(id, user.Id);

                if (request == null)
                    await _requestService.SendRequest(id, user.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Remove/{id}")]
        public async Task<IActionResult> Remove(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
                await _friendService.RemoveFriend(user.Id, id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Reject/{id}")]
        public async Task<IActionResult> Reject(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if ( user != null)
            {
                var request = await _requestService.GetRequest(user.Id, id);

                await _requestService.Reject(request.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Accept/{id}")]
        public async Task<IActionResult> Accept(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                var request = await _requestService.GetRequest(user.Id, id);

                await _requestService.Accept(request.Id);
                await _friendService.AddFriend(user.Id, id);
            }

            return RedirectToAction("Index");
        }
    }
}

RudeAnchorSN/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Models;
using RudeAnchorSN.LogicLayer.Services;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private readonly IRequestService _requestService;
        private readonly IChatService _chatService;

        public UserController(
            ILogger<UserController> logger,
            IUserService userService,
            IRequestService requestService,
            IChatService chatService)
        {
            _logger = logger;
            _userService = userService;
            _requestService = requestService;
            _chatService = chatService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                user.Requests = await _requestService.GetPending(user.Id);
                user.Chats = await _chatService.GetChats(user.Id);
            }

            return View(user);
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Index([FromRoute]int id)
        {
            var currentUser = await _userService.GetUser(User?.Identity?.Name);
            var user = await _userService.GetUser(id);

            if (user != null && currentUser != null)
            {
                user.Requests = await _requestService.GetPending(currentUser.Id);
                user.Chats = await _chatService.GetChats(user.Id);
            }

            return View(user);
        }

        [HttpGet]
        [Route("Edit")]
        public async Task<IActionResult> Edit()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            return View(user);
        }

        [HttpPost]
        [Route("Edit")]
        public async Task<IActionResult> Edit(UserModel user)
        {
            await _userService.UpdateUser(user);

            return RedirectToAction("Index");
        }
    }
}

RudeAnchorSN/Views/Friends/Add.cshtml
@model List<RudeAnchorSN.LogicLayer.Models.UserModel>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Найди друзей";
}

@section css{
    <link rel="stylesheet" href="/css/forms.css" />
    <link rel="stylesheet" href="/css/friends.css" />
}

@section Scripts{
    <script type="text/javascript" src="/js/friends.js"></script>
}

<div class="heading round-corner-box">
    <h1>Зарегестрированные пользователи</h1>
</div>

<div class="breadcrumbs">
    <a asp-action="Index" asp-controller="Friends" class="right white">
        <span class="arrow-left-icon white"></span>
        <span class="white">Назад</span>
    </a>
</div>

<div class="users-container round-corner-box">
    <input type="text" oninput="filterUsers(this);" class="user-filter" placeholder="Введите имя для поиска...">

    @if(Model.Count == 0)
    {
        <p>Видимо кроме вас больше никто не зарегестировался...</p>
    }

    @foreach(var user in Model)
    {
        <div class="user">
            <div class="user-picture-thumb" style="background-image: url(@user.ProfilePicUrl)">
                @if (string.IsNullOrEmpty(user.ProfilePicUrl))
                {
                    <div class="profile-pic-fallback-thumb"></div>
                }
            </div>
            <a asp-action="Index" asp-controller="User" asp-route-id="@user.Id">
                @user.FirstName @user.LastName
            </a>
        </div>
    }
</div>

RudeAnchorSN/Views/Friends/Index.cshtml
@model RudeAnchorSN.LogicLayer.Models.FriendsViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Друзья";
}

<div class="heading round-corner-box">
    <h1>Друзья</h1>
</div>

<div class="breadcrumbs">
    <a asp-action="Index" asp-controller="User" class="right white">
        <span class="arrow-left-icon white"></span>
        <span class="white">Назад</span>
    </a>
</div>

@if(Model.PendingRequests.Count > 0)
{
    <div class="users-container round-corner-box">
        <h2>Заявки в друзья</h2>
        @foreach (var user in Model.PendingRequests)
        {
            <div class="user">
                <div class="user-picture-thumb" style="background-image: url(@user?.ProfilePicUrl)">
                    @if (string.IsNullOrEmpty(user?.ProfilePicUrl))
                    {
                        <div class="profile-pic-fallback-thumb"></div>
                    }
                </div>
                <a asp-action="Index" asp-controller="User" asp-route-id="@user.Id">
                    @user.FirstName @user.LastName
                </a>

                <div class="buttons right">
                    <a asp-action="Accept" asp-controller="Friends" asp-route-id="@user.Id" class="button">
                        Принять
                    </a>
                    <a asp-action="Reject" asp-controller="Friends" asp-route-id="@user.Id" class="button secondary">
                        Отклонить
                    </a>
                </div>
            </div>
        }
    </div>
}

<div class="users-container round-corner-box">
    <h2>У вас в друзьях</h2>

    @if (Model.Friends.Count == 0)
    {
        <p>...никого нет...</p>
    }

    <div style="margin: 10px 0px;">
        <a asp-action="Add" asp-controller="Friends" class="button" style="width: auto;">
            <span>Найти друзей</span>
            <span class="plus-icon"></span>
        </a>
    </div>

    @foreach (var user in Model.Friends)
    {
        <div class="user">
            <div class="user-picture-thumb" style="background-image: url(@user?.ProfilePicUrl)">
                @if (string.IsNullOrEmpty(user?.ProfilePicUrl))
                {
                    <div class="profile-pic-fallback-thumb"></div>
                }
            </div>
            <a asp-action="Index" asp-controller="User" asp-route-id="@user.Id">
                @user.FirstName @user.LastName
            </a>

            <div class="buttons right">
                <a asp-action="Remove" asp-controller="Friends" asp-route-id="@user.Id" class="button secondary">
                    Убрать из друзей
                </a>
            </div>
        </div>
    }
</div>