RudeAnchorSN/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Models;
using RudeAnchorSN.LogicLayer.Services;
using System;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class ChatController : Controller
    {
        private readonly IChatService _chatService;
        private readonly IUserService _userService;
        private readonly ILogger<ChatController> _logger;

        public ChatController(
            IChatService chatService,
            IUserService userService,
            ILogger<ChatController> logger)
        {
            _chatService = chatService;
            _userService = userService;
            _logger = logger;
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Index(int id, [FromQuery]int userId)
        {
            var chat = await _chatService.GetChat(id);
            
            if (chat is null)
            {
                chat = new ChatModel();

                var currentUser = await _userService.GetUser(User?.Identity?.Name);
                var user = await _userService.GetUser(userId);
                var users = new List<UserModel>();

                if (currentUser != null)
                    users.Add(currentUser);

                if (user != null)
                    users.Add(user);

                chat.Users = users;
            }

            var lastMessage = chat?.Messages?.LastOrDefault();

            if (lastMessage != null && lastMessage?.Author?.Email != User?.Identity?.Name)
                await _chatService.MarkAsRead(chat.Id);

            return View(chat);
        }

        [HttpPost]
        [Route("SendMessage")]
        public async Task<IActionResult> SendMessage(
            int chatId,
            int targetUserId,
            string content)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);
            var targetUser = await _userService.GetUser(targetUserId);
            var chat = await _chatService.GetChat(chatId);

            if (chat is null)
                chat = await _chatService.StartChat(new List<UserModel>() { user, targetUser });

            var message = new MessageModel()
            {
                ChatId = chat.Id,
                AuthorId = user.Id,
                Created = DateTime.Now,
                Content = content
            };

            await _chatService.SendMessage(message);

            return RedirectToAction("Index", new { id = chat.Id });
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await _chatService.RemoveChat(id);

            return RedirectToAction("Index", "Messages");
        }
    }
}

RudeAnchorSN/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Services;
using RudeAnchorSN.LogicLayer.Models;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class FriendsController : Controller
    {
        private readonly ILogger<FriendsController> _logger;
        private readonly IUserService _userService;
        private readonly IFriendService _friendService;
        private readonly IRequestService _requestService;

        public FriendsController(
            ILogger<FriendsController> logger,
            IUserService userService,
            IFriendService friendService,
            IRequestService requestService)
        {
            _logger = logger;
            _userService = userService;
            _friendService = friendService;
            _requestService = requestService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);
            var friends = new FriendsViewModel();

            if (user != null)
            {
                friends.PendingRequests = await _requestService.GetPending(user.Id);
                friends.Friends = user.Friends;
            }

            return View(friends);
        }

        [HttpGet]
        [Route("Add")]
        public async Task<IActionResult> Add()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);
            var users = new List<UserModel>();
                
            if (user != null)
                users = await _userService.GetUsers(user.Id);

            return View(users);
        }

        [HttpGet]
        [Route("Add/{id}")]
        public async Task<IActionResult> Add(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                var request = await _requestService.GetRequest(id, user.Id);

                if (request == null)
                    await _requestService.SendRequest(id, user.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Remove/{id}")]
        public async Task<IActionResult> Remove(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
                await _friendService.RemoveFriend(user.Id, id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Reject/{id}")]
        public async Task<IActionResult> Reject(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if ( user != null)
            {
                var request = await _requestService.GetRequest(user.Id, id);

                await _requestService.Reject(request.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Accept/{id}")]
        public async Task<IActionResult> Accept(int id)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                var request = await _requestService.GetRequest(user.Id, id);

                await _requestService.Accept(request.Id);
                await _friendService.AddFriend(user.Id, id);
            }

            return RedirectToAction("Index");
        }
    }
}

RudeAnchorSN/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Models;
using RudeAnchorSN.LogicLayer.Services;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class PostController : Controller
    {
        private readonly ILogger<PostController> _logger;
        private readonly IUserService _userService;
        private readonly IUserPostService _userPostService;

        public PostController(
            ILogger<PostController> logger,
            IUserService userService,
            IUserPostService userPostService)
        {
            _logger = logger;
            _userService = userService;
            _userPostService = userPostService;
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Route("Add")]
        public async Task<IActionResult> Add(
            string title, 
            string content)
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                var newPost = new UserPostModel()
                {
                    UserId = user.Id,
                    DateCreated = DateTime.Now,
                    Title = title,
                    Content = content
                };

                await _userPostService.CreatePost(newPost);
            }

            return RedirectToAction("Index", "User");
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _userPostService.GetPost(id);

            return View(post);
        }

        [HttpPost]
        [Route("Edit")]
        public async Task<IActionResult> Edit(UserPostModel newPost)
        {
            await _userPostService.UpdatePost(newPost);

            return RedirectToAction("Index", "User");
        }
    }
}

RudeAnchorSN/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RudeAnchorSN.LogicLayer.Models;
using RudeAnchorSN.LogicLayer.Services;

namespace RudeAnchorSN.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private readonly IRequestService _requestService;
        private readonly IChatService _chatService;

        public UserController(
            ILogger<UserController> logger,
            IUserService userService,
            IRequestService requestService,
            IChatService chatService)
        {
            _logger = logger;
            _userService = userService;
            _requestService = requestService;
            _chatService = chatService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            if (user != null)
            {
                user.Requests = await _requestService.GetPending(user.Id);
                user.Chats = await _chatService.GetChats(user.Id);
            }

            return View(user);
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Index([FromRoute]int id)
        {
            var currentUser = await _userService.GetUser(User?.Identity?.Name);
            var user = await _userService.GetUser(id);

            if (user != null && currentUser != null)
            {
                user.Requests = await _requestService.GetPending(currentUser.Id);
                user.Chats = await _chatService.GetChats(user.Id);
            }

            return View(user);
        }

        [HttpGet]
        [Route("Edit")]
        public async Task<IActionResult> Edit()
        {
            var user = await _userService.GetUser(User?.Identity?.Name);

            return View(user);
        }

        [HttpPost]
        [Route("Edit")]
        public async Task<IActionResult> Edit(UserModel user)
        {
            await _userService.UpdateUser(user);

            return RedirectToAction("Index");
        }
    }
}

RudeAnchorSN/Views/User/Edit.cshtml
@model RudeAnchorSN.LogicLayer.Models.UserModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Редактирование профиля";
}

@section css {
    <link rel="stylesheet" href="~/css/editProfile.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/forms.css" asp-append-version="true" />
}

@section Scripts {
    <script type="text/javascript" src="~/js/editProfile.js"></script>
}

<div class="heading round-corner-box">
    <h1>Редактирование профиля</h1>
</div>

<div class="form-container">
    @using (Html.BeginForm("Edit", "User", FormMethod.Post))
    {
        <div class="form-line">
            <div id="profile-picture-placeholder" style="background-image: url(@Model.ProfilePicUrl)">
                @if (string.IsNullOrEmpty(Model.ProfilePicUrl))
                {
                    <div class="profile-pic-fallback"></div>
                }
            </div>
            <div>
                <label for="profile-pic-input" class="button profile-pic-input-label">Добавить фото</label>
                <input id="profile-pic-input" type="file" accept=".png,.jpeg,.jpg" name="ProfilePic" style="display:none;">
            </div>
        </div>

        <div class="form-line">
            <div class="form-label">Имя</div>
            <input type="text" name="FirstName" value="@Model.FirstName" required />
        </div>

        <div class="form-line">
            <div class="form-label">Фамилия</div>
            <input type="text" name="LastName" value="@Model.LastName" required />
        </div>

        <div class="form-line">
            <div class="form-label">Email</div>
            <input type="text" readonly name="Email" value="@Model.Email" required />
        </div>

        <div class="form-line">
            <div class="form-label">Город</div>
            <input type="text" name="City" value="@Model.City" required />
        </div>

        <div class="form-line">
            <div class="form-label">О себе</div>
            <input type="text" name="About" value="@Model.About" required />
        </div>

        <input type="hidden" name="ProfilePicUrl" id="profile-pic-hidden" value="@Model.ProfilePicUrl" />
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="LastOnline" value="@Model.LastOnline" />
        <input type="hidden" name="BirthDate" value="@Model.BirthDate" />

        <div class="form-line">
            <div class="col-splitter">
                <button type="submit" style="margin-right: 10px;">Сохранить изменения</button>
                <a asp-action="Index" asp-controller="User" class="button secondary">Отмента</a>
            </div>
        </div>
    }
</div>

RudeAnchorSN/Views/User/Index.cshtml
@model RudeAnchorSN.LogicLayer.Models.UserModel

@{
    Layout = "_Layout";
    ViewData["Title"] = $"{Model.FirstName} {Model.LastName}";
}

@{
    var requestsCount = Model.Requests.Count > 0 ? $"({Model.Requests.Count})" : string.Empty;
    var isOwnPage = User?.Identity?.Name == Model.Email;
    var isInFriends = Model.Friends.Any(x => x.Email == User?.Identity?.Name);
    var newMessagesCount = Model.Chats.Where(x => x.HasNew && x.Messages.LastOrDefault()?.Author?.Email != User?.Identity?.Name).Count();
    var chat = Model.Chats.FirstOrDefault(x => x.Users.Any(y => y.Email == User?.Identity?.Name));
    var chatId = chat is null ? -1 : chat.Id;
}

@section css{
    <link rel="stylesheet" href="/css/user.css" />
}

<div class="heading round-corner-box">
    <h1>
        @Model.FirstName @Model.LastName
    </h1>
</div>

@if (!isOwnPage)
{
    <div class="breadcrumbs">
        <a asp-action="Index" asp-controller="Friends" class="right white">
            <span class="arrow-left-icon white"></span>
            <span class="white">Назад</span>
        </a>
    </div>
}

<div class="wrapper">
    <div class="menu round-corner-box">
        <div id="profile-picture-placeholder" style="background-image: url(@Model.ProfilePicUrl)">
            @if (string.IsNullOrEmpty(Model.ProfilePicUrl))
            {
                <div class="profile-pic-fallback"></div>
            }
        </div>

        @if (isOwnPage)
        {
            <div class="menu-item">
                <a asp-action="Edit">
                    Редактировать профиль
                </a>
            </div>
            <div class="menu-item">
                <a asp-action="Index" asp-controller="Messages">
                    Сообщения @(newMessagesCount > 0 ? $"({newMessagesCount})" : string.Empty)
                </a>
            </div>
            <div class="menu-item">
                <a asp-action="Index" asp-controller="Friends">
                    Друзья @requestsCount
                </a>
            </div>
        }
        else
        {
            @if (Model.Requests.FirstOrDefault(x => x.Id == Model.Id) != null)
            {
                <div class="menu-item">
                    <a asp-action="Accept" asp-controller="Friends" asp-route-id="@Model.Id">
                        Принять
                    </a>
                </div>

                <div class="menu-item">
                    <a asp-action="Reject" asp-controller="Friends" asp-route-id="@Model.Id">
                        Отклонить
                    </a>
                </div>
            }
            else
            {
                if (!isInFriends)
                {
                    <div class="menu-item">
                        <a asp-action="Add" asp-controller="Friends" asp-route-id="@Model.Id">
                            Добавить в друзья
                        </a>
                    </div>
                }
                else
                {
                    <div class="menu-item">
                        <a asp-action="Index" asp-controller="Chat" asp-route-id="@chatId" asp-route-userId="@Model.Id">
                            Написать сообщение
                        </a>
                    </div>
                }
            }
        }
    </div>

    <div class="content-container round-corner-box">
        <div class="profile-data">
            <div class="user-city">
                Город: @Model.City
            </div>

            <div class="user-email">
                Email: @Model.Email
            </div>

            <div class="user-about">
                О себе: @Model.About
            </div>

            <div class="date-of-birth">
                День рождения: @Model.BirthDate.ToShortDateString() (@Model.Age лет)
            </div>

            <div class="last-online">
                Последний раз онлайн: @Model.LastOnline
            </div>
        </div>

        <div class="wall">
            @if (isOwnPage)
            {
                <div class="post-button">
                    <a asp-action="Add" asp-controller="Post" class="button">
                        <span>Добавить пост</span>
                        <span class="plus-icon"></span>
                    </a>
                </div>
            }

            <div class="posts">
                @foreach (var post in Model.Posts)
                {
                    <partial name="_Post.cshtml" model="new RudeAnchorSN.LogicLayer.Models.UserPostViewModel(Model, post)" />
                }
            </div>
        </div>
    </div>
</div>

RudeAnchorSN/Views/User/_Post.cshtml
@model RudeAnchorSN.LogicLayer.Models.UserPostViewModel

@{
    var ownPage = User?.Identity?.Name == Model.Author.Email;
}

<div class="post">
    <div class="post-title">
        <h3>@Model.Post.Title</h3>
    </div>
    <div class="post-content">@Model.Post.Content</div>
    <div class="post-date">
        <em>@Model.Post.DateCreated</em>
    </div>
    @if (ownPage)
    {
        <div class="post-button">
            <a asp-action="Edit" asp-controller="Post" asp-route-id="@Model.Post.Id" class="button secondary">Править</a>
        </div>
    }
</div>